//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utils.Resources.GeneralMessages", typeof(GeneralMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logró identificar la configuración del importe para los vehículos de tipo {0}.
        /// </summary>
        public static string AmountNotFound {
            get {
                return ResourceManager.GetString("AmountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe a pagar para el vehículo con placa: {0} es de: ${1}.
        /// </summary>
        public static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno..
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un vehículo registrado con la placa {0}.
        /// </summary>
        public static string ExistVehicle {
            get {
                return ResourceManager.GetString("ExistVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El módulo de pagos solo está habilitado para vehículos de tipo {0} o {1}.
        /// </summary>
        public static string InvalidVehicleTypeForPaymentModule {
            get {
                return ResourceManager.GetString("InvalidVehicleTypeForPaymentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro guardado satisfactoriamente..
        /// </summary>
        public static string ItemInserted {
            get {
                return ResourceManager.GetString("ItemInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible guardar el registro..
        /// </summary>
        public static string ItemNoInserted {
            get {
                return ResourceManager.GetString("ItemNoInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de pago ingresado no cubre el total de la deuda para el vehículo con placas {0}. La deuda total del vehículo es de ${1}.
        /// </summary>
        public static string LowerPaymentValue {
            get {
                return ResourceManager.GetString("LowerPaymentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede registrar el vehículo debido a que tiene una entrada abierta en el sistema..
        /// </summary>
        public static string NoRegisterInputOpen {
            get {
                return ResourceManager.GetString("NoRegisterInputOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible registrar la {0} del vehículo {1} por que {2} tiene una entrada abierta..
        /// </summary>
        public static string OpenCloseEntrance {
            get {
                return ResourceManager.GetString("OpenCloseEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ingresar un pago con un valor $0.
        /// </summary>
        public static string PaymentGreaterThanZero {
            get {
                return ResourceManager.GetString("PaymentGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha registrado correctamente el pago para el vehículo con placa {0}.
        /// </summary>
        public static string RegisteredPayment {
            get {
                return ResourceManager.GetString("RegisteredPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor a pagar por su estancia es de: $ {0}.
        /// </summary>
        public static string ValueToPayForTheStay {
            get {
                return ResourceManager.GetString("ValueToPayForTheStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vehículo con placas {0} se encuentra a paz y salvo. La próxima fecha de pago es el {1}.
        /// </summary>
        public static string VehicleADay {
            get {
                return ResourceManager.GetString("VehicleADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible validar la información del vehículo con placas {0} y de tipo {1}.
        /// </summary>
        public static string VehicleAndTypeVehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleAndTypeVehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible validar la información del vehículo con placas {0}.
        /// </summary>
        public static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de vehículo especificado no se encuentra configurado en el sistema..
        /// </summary>
        public static string VehicleTypeNotSupported {
            get {
                return ResourceManager.GetString("VehicleTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite el registro de vehículos de tipo {0} o {1}.
        /// </summary>
        public static string VehicleTypeRegistrationNotAllowed {
            get {
                return ResourceManager.GetString("VehicleTypeRegistrationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible configurar un valor de importe para los vehículos de tipo {0}.
        /// </summary>
        public static string VehicleTypeValueAmountInvalid {
            get {
                return ResourceManager.GetString("VehicleTypeValueAmountInvalid", resourceCulture);
            }
        }
    }
}
